<?php include('utils/colors_utils.php'); ?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Choix du thème</title>
</head>
<body style="background-color: <?= isset($_COOKIE['backgroundColor']) ? $_COOKIE['backgroundColor'] : 'white'; ?>;
    color: <?= isset($_COOKIE['backgroundColor']) ? getTextColor($_COOKIE['backgroundColor']) : 'black'; ?>;">
    
    <h1>Choisissez votre thème :</h1>
    <form action="set_theme.php" method="post">
        <label for="colorPicker">Couleur de fond :</label>
        <input type="color" id="colorPicker" name="colorPicker">
        <button type="submit" name="applyTheme">Appliquer</button>
    </form>
    <p><a href="delete_cookie.php">Supprimer le cookie</a></p>
    

</body>
</html>